version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client
    environment:
      - PATH_URL_BACKEND=http://127.0.0.1:8000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./app/node_modules
